### PR TITLE
Blink OK LED while transmitting

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Blink the LED at every symbol when "-l" is supplied.

### CODE REVIEW

**Comment by JamesP6000** [comment]
Hi Frederico,

This is a really neat feature!

Does this work both on the Pi v1 and also the Pi v2?

Also, it seems from the code that the LED blinking feature is always turned
on and cannot be turned off? I don't see any way for blink_led to ever have
the value false? I think the best user interface is to have blink_led be
true by default, but if the user uses the command line option, they can
turn off the led blinking.

James


On Thu, Oct 22, 2015 at 11:16 AM, Federico Ceratto <notifications@github.com

**Comment by FedericoCeratto** [comment]
There are claims that the OK LED can be controlled on Pi v2 as well:
https://raspberrypi.stackexchange.com/questions/697/how-do-i-control-the-system-leds-using-my-software/27929
I don't have a v2 to test this hence I made the "-l" flag opt-in.
(Also the other -r -o -s flags are disabled by default)

**Comment by michelinok** [comment]
It would be great if we can specify the gpio number to "blink"....I would like to connect an external led and blink it while transmitting...
Is this possible?

**Comment by Supremehamster** [comment]
Got it working on my Pi2b (flashing green led - no gpio) - code is here .... only wspr.cpp is different 
https://github.com/Supremehamster/WsprryPiLed/commit/df55a60f84196bf454eb61510fa7cc476c5c1913
Used Federico's code and put it where I guessed it should go lol ;)

**Comment by FedericoCeratto** [comment]
@michelinok I can't test code changes at the moment, perhaps you could send a PR if/after @JamesP6000 merges this one?

**Comment by Supremehamster** [comment]
@michelinok @JamesP6000 Would be nice to merge if James wishes to. I was wondering if adding code has any timing implications? Seems to be ok - mines gone 100km on 100mw (20m) so looking good here.

**Comment by dl9sec** [comment]
Hi,
i am not very familiar with this github stuff and i don't have a own repository, but the attached patch will give you the suggested TX blink-LED function with the latest sources:
[wspr_blinkledtx.zip](https://github.com/JamesP6000/WsprryPi/files/1906878/wspr_blinkledtx.zip)
I tested it on a good old Raspi 1...
Regards, Thorsten DL9SEC

**Pull request closed without merging**
